void delay_ms(unsigned int );
void lcd_init(void);
void lcd_int(int );
void lcd_float(float );
void lcd_cmd(unsigned char ); 
void lcd_data(unsigned char );
void lcd_str(unsigned char*);
unsigned int adc_read(void);
void ultrasonic_trigger(void);
unsigned int get_echo_time(void);
unsigned int get_distance(void);
void timer1_init(void);
